src/App.vue
Hey i want to contribute your issue: logo and header link to homepage
=> feat: logo and header link to home page

src/recipes/beer-pletok.json, src/recipes/caipirinha.json, src/recipes/corn-juice.json, src/recipes/cosmopolitan.json, src/recipes/ginger-milk-tea.json, src/recipes/hot-espresso.json, src/recipes/margarita.json
Corrected typos found on the recipe list
=> corrected found typos

src/App.vue
=> Fix #38 Add mb to app

src/components/RecipeFind.vue
On the 'search'-page it can be selected whether to search for the names or the ingredients of the drinks (or both). Recipes containing multiple desired ingredients can also be found by separating the ingredients with a space.
=> Recipes are searchable by ingredients

CONTRIBUTING.md, src/components/Recipe.vue, src/recipes/ginger-milk-tea.json
- _CONTRIBUTING.md_
- provide an example to add drink tags
- _src/components/Recipe.vue_
- display tags after drink title
- _src/recipes/ginger-milk-tea.json_
- example of drink with tags
=> Added option to include keywords

src/recipes/yellow-watermelon-juice.json, src/recipes/yogurt-fruit-shake.json, src/recipes/zombie.json
add key words for zombie, yellow watermelon juice, and yogurt fruit shake
=> add key words for zombie, yellow watermelon juice, and yogurt fruit

src/components/RecipeFind.vue
resolves #124
Revised the way recipes are found. Now we first filter based on the given parameters and then we sort the output of that if needed i.e. the user searched for a drink by name.
=> revised the algorithm for finding recipes

src/recipes/aam-panna.json, src/recipes/aperol-spritz.json, src/recipes/april-rain.json, src/recipes/aviation.json
Adding keywords to the recipes of "Aam panna", "Aperol spritz", "April rain" and "Aviation".
=> adding keywords to some recipes

src/recipes/barley-drink.json, src/recipes/beer-pletok.json, src/recipes/bikini-martini.json
- fixed barley-drink recipe;
- keywords added to Barley Drink, Beer Pletok and Bikini Martini.
=> fixing barley-drink recipe and adding keywords

src/recipes/pear-manhattan-cocktail.json
=> Improved formatting and typos

src/recipes/tom-collins.json, src/recipes/vampiro.json, src/recipes/vodka-martini.json, src/recipes/whisky-sour.json
=> Add keywords to a few drinks

src/components/RecipeList.vue
Noticed the need for Pagination and dropdown field on #163 issue 
Happy Hacktoberfestt!  🎃
=> Add Pagination and Dropdown Menu to Explore Tab

src/components/Recipe.vue, src/router.js, src/views/PrintRecipe.vue
I've tried to implement it in a way that even if the component gets re-used, it only prints its content. Without losing the styles while printing. If there are any adjustments, or suggestions I'd love to hear it from you guys. #133
=> Adds print option on recipe component

src/recipes/paloma.json, src/recipes/panty-ripper.json, src/recipes/pear-manhattan-cocktail.json, src/recipes/pimms.json, src/recipes/pina-colada.json, src/recipes/pineapple-juice.json, src/recipes/pisco-sour.json, src/recipes/planters-punch.json, src/recipes/purple-haze.json, src/recipes/red-wine-spritzer.json, src/recipes/sangria.json, src/recipes/savage-banana-soup.json, src/recipes/screwdriver.json, src/recipes/sea-breeze.json, src/recipes/sex-on-the-beach.json, src/recipes/smirnoff-black-russian.json, src/recipes/sonic-screwdriver.json
=> add keywords to drinks P-S

src/App.vue, src/components/Recipe.vue, src/components/RecipeList.vue, src/recipes/index.js, src/router.js, src/views/Explore.vue, src/views/Keyword.vue, src/views/KeywordList.vue
I found myself wishing the keyword badges were clickable and a way to view all of the keywords. This PR adds a two new pages. One that shows all of the unique keywords and one that shows all drinks that have a given keyword. Plus now the keyword badges are clickable so you can see other similar drinks more easily.
=> Add views for seeing all drinks that have a particular keyword

src/components/RecipeFind.vue, src/recipes/sunshine-cocktail.json
Some cleanup and linting. This may not work 1:1 on the previous search, but trying to simplify the search feature.
=> Update search function

src/recipes/drunken-monkey.json, src/recipes/dutchmans-daiquiri.json, src/recipes/gimlet.json
added keywords for a few drinks on #139
=> added keywords for a few drinks

src/views/Home.vue
Fix history loop.
You can not go back because you are pushing the user further from landing page.
=> fix going back loop

src/components/RecipeList.vue, src/recipes/index.js, src/views/Explore.vue
On the explore page the drinks are filterable by keyword.
Only the keywords that are used in multiple drinks (5 for now) are selectable.
The UI may still need some work, but the functionality is there.
=> 192 sorting and filtering on explore view

src/components/RecipeFind.vue
Upgraded search:
- exclusive search instead of inclusive
- alphabetical order (no more flickering)
=> feat: exclusive search && alphabetical order

src/recipes/moscow-mule-simple.json
An alternate Moscow Mule with ingredients you are more likely to have on hand.
=> Simple moscow mule

README.md
Testing Github Actions - Test Workflow.
=> Testing Github Actions - Test Workflow

src/views/Explore.vue
Closes #248 
Filters can be shown/hidden with the press of a button
=> Multiple keywords are selectable fo filtering

src/components/Recipe.vue, src/components/RecipeTile.vue
Updates the RecipeTile component for "Similar Drinks". 
* Update UI to be a bit more minimal using b-card
* Title and Image link to the drink
* Remove footer from b-card and View Recipe button
=> Update the similar drinks - RecipeTile card UI.

src/recipes/aam-panna.json, src/recipes/caipiroska.json, src/recipes/christmas-tonic.json, src/recipes/coconut-mint-collins.json, src/recipes/hi-fi.json
=> added important keywords

tests/unit/components/Recipe.spec.js
Test whether the recipe keywords loads correctly in the Recipe component.
=> added test for Recipe component

src/App.vue, src/components/FeaturedRecipes.vue, src/featured.json, src/recipes/index.js, src/router.js, src/views/Featured.vue
A new view to display featured drinks customized via `src/featured.json`. This will be a way for us to configure a homepage of featured drinks categories.
Thanks to the RecipeTile component by @TobyAsE, this made it easy!
=> New Featured Drinks View

package-lock.json, src/featured.json
added/tested on dev environment new sick or health promoting featured drink section, per new featured.json - hacktoberfest request
=> sick or health promoting featured drink section add

src/components/RecipeFind.vue
As I am new to Vue JS, I have done most of the functionality in the <script> tag. If there is a better way to do it, please feel free to comment.
Functionality: (circular way)
1. After typing when down-arrow is clicked, it will select the first drink and navigate downwards.
2. Clicking up-arrow will navigate upwards.
3. Initially if up-arrow is clicked, last element is selected.
#357
=> [Feature] Keyboard controls on search view results

src/featured.json
* added added new cateogry to the featured.json page.
* category is strong drinks
* includes sazerac, long island iced team, zombie, and black russian
=> Strong Drinks Category

tests/unit/components/RecipeList.spec.js
I added some tests for the RecipeList component.
=> Add spec for the RecipeList component

tests/unit/views/Explore.spec.js
I added some tests for the Explore view.
=> Add some tests for the Explore view

tests/unit/components/RecipeTile.spec.js
Hey ! 
I figured i'd add some test for `RecipeTile.vue`  (#281) 
Don't hesitate to give some feedback or ask for changes
Thanks :)
=> Add test for RecipeTile component

tests/unit/views/Favorites.spec.js
#281 
- Test to remove an recipe from your favorites
=> Add more unit tests

src/views/Favorites.vue
#307 
- Remove button should be red
- give the button some space
=> Change some design

src/router.js, src/views/Favorites.vue, src/views/PageNotFound.vue
- better than an empty page/ router out
=> Add 404 PageNotFound Component

src/featured.json
New category added which does contain all drinks which do contain milk.
=> Add new featured category milky heaven

tests/unit/views/Search.spec.js
Add test for the search page when name is selected (Issue #281)
=> Add test for search page

src/recipes/blood-and-sand.json, src/recipes/greyhound.json
Updates for blood&sand and greyhound
=> Recipe cleanup

src/recipes/trash-can.json
Added Trash Can recipe and image. A personal favorite!
=> Add Trash Can

jest.config.js, tests/unit/components/FeaturedRecipes.spec.js
I add jest coverage summary to help others to contribute on unit test. I also add unit test on FeaturedRecipes. Kindly check and review my pull request :pray: 
Please delete options that are not relevant.
=> Add Jest Coverage Summary and Add More Test

src/recipes/aam-panna.json, src/recipes/aamras.json, src/recipes/amaretto-sour.json, src/recipes/amf.json, src/recipes/aperol-spritz.json, src/recipes/appletini.json, src/recipes/b-52.json, src/recipes/banana-smoothie.json
I corrected some grammar errors. Please review these.
=> Some grammar errors

src/recipes/bangkok-sunrise.json, src/recipes/cucumber-gin.json, src/recipes/madras.json, src/recipes/strawberry-saquerinha.json, src/recipes/tea-ais.json, src/recipes/tropical-sangria.json, src/recipes/velvet-elvis.json, src/recipes/vodka-schweppes.json
Fixed a couple of typos I noticed in the recipes, especially in the tea-ais.json file. Hope this helps!
=> Fixed typos in recipes

CONTRIBUTING.md
Add direction and ressource to help contributers making sure they have a valid JSON file before making a Pull Request.
=> Add description and resource to validate JSON file before pull request

src/recipes/mango-lassi.json, src/recipes/nimbu-pani.json
=> Fix typos in recipes #766

src/recipes/barraquito.json
Adding the official name of the islands so more people can find this delicious recipe 😄 
https://en.wikipedia.org/wiki/Canary_Islands
=> Add `Canary Islands` to barraquito recipe

src/recipes/pok-shot.json
Fixing some grammar to make this recipe more legible.
Thanks for this repo, very useful.
=> Fix typos in pok shot recipe

src/recipes/creamy-mango-lassi.json
Small fixes to improve the recipe.
=> Cleanup creamy mango lassi recipe

src/recipes/negroni.json
This is my favorite cocktail, partly because of how simple it is to make.
Adding the `simple` tag to it like other easy cocktails have in this catalogue. More people should find it and try it.
=> Add `simple` tag to the Negroni recipe

src/recipes/pomegranate-lemon-mint.json
Fixing the formatting to match the rest of the recipes.
The file was also in DOS format, converted it to UNIX format.
=> Fix the formatting of pomegranate-lemon-mint.json

src/components/Recipe.vue, src/views/Keyword.vue
current : when user choose recipe in similar menu or explore it can't see the content.
=> [enhance] scroll window after choose recipe

src/components/RecipeToolbar.vue, tests/unit/components/Recipe.spec.js
situation : when user star on recipe and then change the menu
issues : 
- recipe toolbar not update star active/inactive
solutions :
- use computed variable instead of data
=> [fix]  : favorite recipe not update when change recipe

src/components/RecipeToolbar.vue
Just a suggestion, take it or leave it :)
=> Feature suggestion - Add copy url to share dropdown

src/recipes/savage-banana-soup.json
I realised (2 years later) that there was a spelling mistake. The recipe is ground ginger not gin! Plus some tweaks to weights etc.
=> Fixes typo and amounts

src/lang/fr.js
Modifications to fix #1385 pipeline warnings
=> Fix fr i18n reviews

src/components/RecipeTile.vue
This pull request implements a hover effect on recipe cards displayed in the RecipeTile.vue component.
- When a user hovers over a recipe card, it now shows a subtle shadow and slight scale-up animation to improve interactivity and visual engagement.
- Changes were made by adding scoped CSS inside RecipeTile.vue.
- Manually tested on localhost.
- Verified that hovering over recipe cards triggers the intended visual effect without affecting layout, links, or functionality.
Closes [#1413](https://github.com/alfg/opendrinks/issues/1413)
=> Add hover effect to recipe cards for website interactivity
